language: cpp
compiler:
 - gcc
 - g++

before_install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "yes" |sudo apt-add-repository ppa:zoogie/sdl2-snapshots; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y gcc-4.8 g++-4.8 libsdl-* libglm-dev libglew-dev libsdl2-dev python python-dev libboost-all-dev libboost-python-dev libboost-python1.48.0; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glew; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glm; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install homebrew/x11/mesalib-glw; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glfw2; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glfw3; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew unlink boost; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install boost --with-python; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install boost-python --with-python; fi


script:
 - chmod 755 configure
 - autoreconf -i
 - ./configure
 - make

os:
 - linux
 - osx

matrix:
  allow_failures:
    - os: osx

sudo: true
